### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Shaxzy** [HerrEurobeat/steam-mass-comment-bot#2]
I'm sorry. I am probably just blind to not understand this. However I did everything as described, I don't see why I get such error.
```
PS C:\Users\henni\Desktop\steam-mass-comment-bot-master> node index.js
internal/modules/cjs/loader.js:984
  throw err;
  ^

Error: Cannot find module 'steam-user'
Require stack:
- C:\Users\henni\Desktop\steam-mass-comment-bot-master\index.js
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:981:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:863:27)[39m
[90m    at Module.require (internal/modules/cjs/loader.js:1043:19)[39m
[90m    at require (internal/modules/cjs/helpers.js:77:18)[39m
    at Object.<anonymous> (C:\Users\henni\Desktop\steam-mass-comment-bot-master\index.js:14:19)
[90m    at Module._compile (internal/modules/cjs/loader.js:1157:30)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:1001:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:900:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\henni\\Desktop\\steam-mass-comment-bot-master\\index.js'[39m
  ]
}
PS C:\Users\henni\Desktop\steam-mass-comment-bot-master>
```

**Comment by Shaxzy** [comment]
nvm I fixed it. stupid me forgot to do npm install xd
