### ISSUE TITLE
Cant run

### ISSUE THREAD

**Issue by DrunkenBlyatHvH** [HerrEurobeat/steam-mass-comment-bot#7]
node index.js 
node:internal/modules/cjs/loader:1170
    throw err;
    ^

SyntaxError: /home/***/Cheat/steam-mass-comment-bot/logininfo.json: Unexpected token { in JSON at position 122
    at parse (<anonymous>)
    at Object.Module._extensions..json (node:internal/modules/cjs/loader:1167:22)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/***/Cheat/steam-mass-comment-bot/index.js:21:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)

**Comment by DrunkenBlyatHvH** [comment]
npm audit fix --force
npm WARN using --force Recommended protections disabled.
npm WARN audit Updating fix to 0.0.3,which is a SemVer major change.

removed 2 packages, changed 2 packages, and audited 289 packages in 2s

24 packages are looking for funding
  run `npm fund` for details

# npm audit report

lodash  <=4.17.20
Severity: critical
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
Prototype Pollution in lodash - https://github.com/advisories/GHSA-jf85-cpcp-j695
Prototype pollution in lodash - https://github.com/advisories/GHSA-x5rq-j2xg-h7qm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-fvqr-27wr-82fm
fix available via `npm audit fix`
node_modules/lodash
  cheerio  0.14.0 - 1.0.0-rc.3
  Depends on vulnerable versions of css-select
  Depends on vulnerable versions of lodash
  node_modules/cheerio
    steamcommunity  2.3.0 - 3.30.2
    Depends on vulnerable versions of cheerio
    node_modules/steamcommunity

nth-check  <2.0.1
Severity: moderate
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix`
node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/css-select
    cheerio  0.14.0 - 1.0.0-rc.3
    Depends on vulnerable versions of css-select
    Depends on vulnerable versions of lodash
    node_modules/cheerio
      steamcommunity  2.3.0 - 3.30.2
      Depends on vulnerable versions of cheerio
      node_modules/steamcommunity

5 vulnerabilities (2 moderate, 3 critical)

To address all issues, run:
  npm audit fix

**Comment by DrunkenBlyatHvH** [comment]
npm audit fix
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'fix@0.0.3',
npm WARN EBADENGINE   required: { node: '0.2.5' },
npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.1.2' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pipe@0.0.1',
npm WARN EBADENGINE   required: { node: '0.2.5' },
npm WARN EBADENGINE   current: { node: 'v16.13.1', npm: '8.1.2' }
npm WARN EBADENGINE }

up to date, audited 289 packages in 1s

24 packages are looking for funding
  run `npm fund` for details

# npm audit report

lodash  <=4.17.20
Severity: critical
Command Injection in lodash - https://github.com/advisories/GHSA-35jh-r3h4-6jhm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-p6mc-m468-83gw
Prototype Pollution in lodash - https://github.com/advisories/GHSA-jf85-cpcp-j695
Prototype pollution in lodash - https://github.com/advisories/GHSA-x5rq-j2xg-h7qm
Prototype Pollution in lodash - https://github.com/advisories/GHSA-fvqr-27wr-82fm
fix available via `npm audit fix`
node_modules/lodash
  cheerio  0.14.0 - 1.0.0-rc.3
  Depends on vulnerable versions of css-select
  Depends on vulnerable versions of lodash
  node_modules/cheerio
    steamcommunity  2.3.0 - 3.30.2
    Depends on vulnerable versions of cheerio
    node_modules/steamcommunity

nth-check  <2.0.1
Severity: moderate
Inefficient Regular Expression Complexity in nth-check - https://github.com/advisories/GHSA-rp65-9cf3-cjxr
fix available via `npm audit fix`
node_modules/nth-check
  css-select  <=3.1.0
  Depends on vulnerable versions of nth-check
  node_modules/css-select
    cheerio  0.14.0 - 1.0.0-rc.3
    Depends on vulnerable versions of css-select
    Depends on vulnerable versions of lodash
    node_modules/cheerio
      steamcommunity  2.3.0 - 3.30.2
      Depends on vulnerable versions of cheerio
      node_modules/steamcommunity

5 vulnerabilities (2 moderate, 3 critical)

To address all issues, run:
  npm audit fix

**Comment by HerrEurobeat** [comment]
> node index.js node:internal/modules/cjs/loader:1170 throw err; ^
> 
> SyntaxError: /home/_**/Cheat/steam-mass-comment-bot/logininfo.json: Unexpected token { in JSON at position 122 at parse () at Object.Module._extensions..json (node:internal/modules/cjs/loader:1167:22) at Module.load (node:internal/modules/cjs/loader:981:32) at Function.Module._load (node:internal/modules/cjs/loader:822:12) at Module.require (node:internal/modules/cjs/loader:1005:19) at require (node:internal/modules/cjs/helpers:102:18) at Object. (/home/**_/Cheat/steam-mass-comment-bot/index.js:21:19) at Module._compile (node:internal/modules/cjs/loader:1101:14) at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10) at Module.load (node:internal/modules/cjs/loader:981:32)

Looks like you have a Syntax error in your `logininfo.json`. Please make sure you are exactly following the syntax of the template.  



> npm audit fix --force npm WARN using --force Recommended protections disabled. npm WARN audit Updating fix to 0.0.3,which is a SemVer major change.
> 
> removed 2 packages, changed 2 packages, and audited 289 packages in 2s
> 
> 24 packages are looking for funding run `npm fund` for details
> # npm audit report
> 
> lodash <=4.17.20 Severity: critical Command Injection in lodash - [GHSA-35jh-r3h4-6jhm](https://github.com/advisories/GHSA-35jh-r3h4-6jhm) Prototype Pollution in lodash - [GHSA-p6mc-m468-83gw](https://github.com/advisories/GHSA-p6mc-m468-83gw) Prototype Pollution in lodash - [GHSA-jf85-cpcp-j695](https://github.com/advisories/GHSA-jf85-cpcp-j695) Prototype pollution in lodash - [GHSA-x5rq-j2xg-h7qm](https://github.com/advisories/GHSA-x5rq-j2xg-h7qm) Prototype Pollution in lodash - [GHSA-fvqr-27wr-82fm](https://github.com/advisories/GHSA-fvqr-27wr-82fm) fix available via `npm audit fix` node_modules/lodash cheerio 0.14.0 - 1.0.0-rc.3 Depends on vulnerable versions of css-select Depends on vulnerable versions of lodash node_modules/cheerio steamcommunity 2.3.0 - 3.30.2 Depends on vulnerable versions of cheerio node_modules/steamcommunity
> 
> nth-check <2.0.1 Severity: moderate Inefficient Regular Expression Complexity in nth-check - [GHSA-rp65-9cf3-cjxr](https://github.com/advisories/GHSA-rp65-9cf3-cjxr) fix available via `npm audit fix` node_modules/nth-check css-select <=3.1.0 Depends on vulnerable versions of nth-check node_modules/css-select cheerio 0.14.0 - 1.0.0-rc.3 Depends on vulnerable versions of css-select Depends on vulnerable versions of lodash node_modules/cheerio steamcommunity 2.3.0 - 3.30.2 Depends on vulnerable versions of cheerio node_modules/steamcommunity
> 
> 5 vulnerabilities (2 moderate, 3 critical)
> 
> To address all issues, run: npm audit fix

This project hasn't been updated in quite a while, so a few packages are out-of-date.  
Just run `npm install` and ignore the warnings, the packages will still install without problems.  
You don't need to run `npm audit` or something other than just `npm install`.

**Comment by DrunkenBlyatHvH** [comment]
ok its running now

**Comment by DrunkenBlyatHvH** [comment]
can you tell me how i can command with more than one account ?

**Comment by DrunkenBlyatHvH** [comment]
{
	"accountName": "l***",
	"password": "***",

	"accountName": "***",
	"password": "***",


	"accountName": "***",
	"password": "***",


	"accountName": "***",
	"password": "***",


	"accountName": "***",
	"password": "***"
}

**Comment by DrunkenBlyatHvH** [comment]
i tried like this but its only using one account

**Comment by HerrEurobeat** [comment]
This bot only supports commenting with one account on many profiles.  
If you want to comment with many accounts on one profile, then check out my [comment-service-bot](https://github.com/HerrEurobeat/steam-comment-service-bot), which is also a bit more popular.

**Comment by DrunkenBlyatHvH** [comment]
ok thank you

**Comment by HerrEurobeat** [comment]
No problem!
